In [ ]:
import pandas as pd
from collections import Counter
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

## 2021

In [ ]:
q1_path = '/content/drive/MyDrive/CHINA_HATE/2022/2022_Q1.csv'
q1 = pd.read_csv('/content/drive/MyDrive/CHINA_HATE/2022/2022_Q1.csv')

<ipython-input-5-09b441261c56>:2: DtypeWarning: Columns (0,4,6,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  q1 = pd.read_csv('/content/drive/MyDrive/CHINA_HATE/2022/2022_Q1.csv')

In [ ]:
q2_path = '/content/drive/MyDrive/CHINA_HATE/2022/2022_Q2.csv'
q2 = pd.read_csv('/content/drive/MyDrive/CHINA_HATE/2022/2022_Q2.csv', lineterminator='\n')

In [ ]:
q3_path = '/content/drive/MyDrive/CHINA_HATE/2022/2022_Q3.csv'
q3 = pd.read_csv('/content/drive/MyDrive/CHINA_HATE/2022/2022_Q3.csv')

<ipython-input-9-9f3a34089c3d>:2: DtypeWarning: Columns (0,4,6,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  q3 = pd.read_csv('/content/drive/MyDrive/CHINA_HATE/2022/2022_Q3.csv')

In [ ]:
q4_path = '/content/drive/MyDrive/CHINA_HATE/2022/2022_Q4.csv'
q4 = pd.read_csv('/content/drive/MyDrive/CHINA_HATE/2022/2022_Q4.csv', lineterminator='\n')

In [ ]:
df_2022 = pd.concat([q1, q2, q3, q4], axis=0)

In [ ]:
df_na = df_2022[df_2022.isna().any(axis=1)]

In [ ]:
df_2022 = df_2022.fillna(0)

In [ ]:
df_2022[['CARDIFFNLP_ROBERTA_PREDS', 'hateXplain_PREDS', 'COVID_HATE_BERT_PREDS']] = df_2022[['CARDIFFNLP_ROBERTA_PREDS', 'hateXplain_PREDS', 'COVID_HATE_BERT_PREDS']].astype(int)

In [ ]:
df_2022

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,COVID_HATE_BERT_PREDS
0,0,0.0,0.0,1.358857e+18,2022-03-31 23:58:25+00:00,1.509682e+18,en,1.0,0.0,0.0,0.0,unk,Peterson Institute: #China's inbound foreign d...,0,1,0
1,1,1.0,1.0,1.467274e+18,2022-03-31 23:56:35+00:00,1.509681e+18,en,1.0,0.0,0.0,0.0,unk,Today’s country of the day is Myanmar which ha...,0,1,0
2,2,2.0,2.0,1.473836e+18,2022-03-31 23:56:09+00:00,1.509681e+18,en,1.0,1.0,0.0,0.0,unk,Chinese Social Media Giant Blocks Accounts Ass...,0,1,0
3,3,3.0,3.0,1.246628e+18,2022-03-31 23:55:46+00:00,1.509681e+18,en,0.0,0.0,0.0,0.0,unk,"#China, #Russian Continue ‘Limitless #friendsh...",0,1,0
4,4,4.0,4.0,1.492126e+18,2022-03-31 23:55:12+00:00,1.509681e+18,en,22.0,0.0,1.0,4.0,unk,It's a pleasure to be guest with Arnþór Helgas...,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237668,237668,237668.0,237668.0,3.328012e+09,2022-10-08 04:48:01+00:00,1.578608e+18,en,211.0,2.0,9.0,88.0,unk,1/2 \n~Did you know this isn't the 1st time In...,0,1,0
237669,237669,237669.0,237669.0,1.498981e+18,2022-10-08 04:44:20+00:00,1.578607e+18,en,0.0,0.0,0.0,0.0,unk,Highly condemn this shameful act from these co...,0,1,0
237670,237670,237670.0,237670.0,4.503010e+09,2022-10-08 04:43:40+00:00,1.578607e+18,en,0.0,0.0,0.0,1.0,unk,China Using Machine Guns to Enforce Airport Lo...,0,1,0
237671,237671,237671.0,237671.0,1.440959e+18,2022-10-08 04:43:29+00:00,1.578607e+18,en,41.0,0.0,0.0,5.0,unk,"Located at the border between Qiaokou Town, Su...",0,1,0
237672,237672,237672.0,237672.0,1.248672e+18,2022-10-08 04:43:04+00:00,1.578607e+18,en,0.0,0.0,1.0,0.0,unk,China's People's Liberation Army 73021部队 has a...,0,1,0

In [ ]:
Counter(df_2022['COVID_HATE_BERT_PREDS'])

Counter({0: 1110075, 2: 10983, 1: 2813})

In [ ]:
df_2022['COVID_HATE_BERT_PREDS']

0         0
1         0
2         0
3         0
4         0
         ..
237668    0
237669    0
237670    0
237671    0
237672    0
Name: COVID_HATE_BERT_PREDS, Length: 1123871, dtype: int64

In [ ]:
len_df = len(df_2022)
COVID_HATE_BERT_PREDS_bin = []
hateXplain_PREDS_bin = []

covid_hate_preds = list(df_2022['COVID_HATE_BERT_PREDS'])
hatexplain_preds = list(df_2022['hateXplain_PREDS'])

for i in range(len_df):
  if covid_hate_preds[i] == 2:
    COVID_HATE_BERT_PREDS_bin.append(1)
  else:
    COVID_HATE_BERT_PREDS_bin.append(0)
  
  if hatexplain_preds[i] == 0:
    hateXplain_PREDS_bin.append(1)
  else:
    hateXplain_PREDS_bin.append(0)

df_2022['COVID_HATE_BERT_PREDS_bin'] = COVID_HATE_BERT_PREDS_bin
df_2022['hateXplain_PREDS_bin'] = hateXplain_PREDS_bin

In [ ]:
voting_2022 = []

cardiff_preds = list(df_2022['CARDIFFNLP_ROBERTA_PREDS'])

for i in range(len_df):

  votes = []
  votes.append(COVID_HATE_BERT_PREDS_bin[i])
  votes.append(cardiff_preds[i])
  votes.append(hateXplain_PREDS_bin[i])

  voting_2022.append(max(set(votes), key = votes.count))

df_2022['voting_results'] = voting_2022
Counter(voting_2022)

Counter({0: 1122932, 1: 939})

In [ ]:
df_2022_hate = df_2022.loc[df_2022['voting_results']==1]
df_2022_hate

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,COVID_HATE_BERT_PREDS,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
2306,2306,2306.0,2306.0,1.016883e+18,2022-03-31 05:44:55+00:00,1.509406e+18,en,0.0,0.0,0.0,1.0,unk,https://t.co/7VRxce9gJZ\n#India has exhausted ...,0,0,2,1,1,1
2986,2986,2986.0,2986.0,2.395508e+08,2022-03-30 23:16:34+00:00,1.509309e+18,en,1.0,0.0,0.0,0.0,unk,#Censorship #TwitterPolice #Transgender #RonDe...,1,1,2,1,0,1
3552,3552,3552.0,3552.0,1.102143e+18,2022-03-30 16:38:48+00:00,1.509209e+18,en,8.0,0.0,1.0,3.0,unk,#China will be used by mahaYogi to eradicate A...,1,1,2,1,0,1
4511,4511,4511.0,4511.0,1.307598e+18,2022-03-30 10:06:58+00:00,1.509110e+18,en,6.0,0.0,2.0,1.0,unk,#MQM #BAP &amp; #neutral\nWelcome to the new l...,0,0,2,1,1,1
8688,8685,8685.0,8685.0,1.497615e+18,2022-03-28 19:28:28+00:00,1.508526e+18,en,0.0,0.0,0.0,0.0,unk,"China china, where are you?\nGive your doggy o...",1,1,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229815,229815,229815.0,229815.0,7.355947e+17,2022-10-11 20:34:57+00:00,1.579934e+18,en,2.0,0.0,0.0,0.0,unk,"China, you can have your aggravating STINK BUG...",1,1,2,1,0,1
229824,229824,229824.0,229824.0,1.576602e+18,2022-10-11 20:28:16+00:00,1.579932e+18,en,7.0,0.0,0.0,0.0,unk,sending my dick to everyone who like or dm me🍆...,1,0,0,0,1,1
230067,230067,230067.0,230067.0,4.516522e+08,2022-10-11 17:28:49+00:00,1.579887e+18,en,0.0,0.0,0.0,0.0,unk,#Fentanyl is a chemical weapon. #China produce...,1,1,2,1,0,1
231728,231728,231728.0,231728.0,4.742385e+08,2022-10-11 03:47:36+00:00,1.579680e+18,en,0.0,0.0,0.0,0.0,unk,To let all you fucking nuggets slaves worldwid...,0,0,2,1,1,1
236524,236524,236524.0,236524.0,3.331268e+08,2022-10-08 19:04:12+00:00,1.578824e+18,en,2.0,0.0,0.0,3.0,unk,$22.95 - 2 Skunks China Bone Shiken Japan Vint...,0,0,2,1,1,1

In [ ]:
samples_2022 = df_2022_hate.sample(n=800)
samples_2022

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,COVID_HATE_BERT_PREDS,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
148998,148998,148998.0,148998.0,4.827201e+09,2022-04-26 11:32:27+00:00,1.518916e+18,en,1.0,0.0,0.0,6.0,unk,"AoxiPRNew: Somewhere in #China, #BigWhites are...",1,0,0,0,1,1
192794,192794,192794.0,192794.0,1.266662e+18,2022-04-08 02:35:47+00:00,1.512258e+18,en,1.0,0.0,0.0,1.0,unk,China warns every nation.\nWants World to toe ...,1,1,2,1,0,1
27208,27208,27208.0,27208.0,3.318161e+09,2022-12-21 06:59:32+00:00,1.605458e+18,en,1.0,0.0,0.0,0.0,unk,#WORLD #UK #USA #JAPAN #ASIA #CHINA #AFRICA #C...,1,1,2,1,0,1
47719,47719,47719.0,47719.0,1.552536e+18,2022-12-14 00:08:02+00:00,1.602818e+18,en,392.0,0.0,2.0,32.0,unk,Who wants to play with me? Dms open~❤️\n\n#nsf...,1,0,0,0,1,1
93884,93873,93873.0,93873.0,1.497266e+18,2022-02-28 01:03:49+00:00,1.498102e+18,en,0.0,0.0,3.0,0.0,unk,hey #china and #japan AND #taiwan and #malaysi...,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260123,173784,173784.0,173784.0,4.223711e+09,2022-08-03 00:33:54+00:00,1.554627e+18,en,0.0,0.0,0.0,0.0,unk,"#CHINA =PAPER TIGER, THEY RELY ON OUR INFLATED...",1,1,2,1,0,1
210103,173266,173266.0,173266.0,1.352572e+09,2022-01-30 16:34:20+00:00,1.487827e+18,en,0.0,0.0,0.0,0.0,unk,I am not with these corrupted evil racist terr...,1,2,2,1,0,1
141603,141603,141603.0,141603.0,1.016883e+18,2022-11-14 23:54:22+00:00,1.592305e+18,en,0.0,0.0,0.0,0.0,unk,Mofos wanna bend #rules to accommodate their p...,1,0,2,1,1,1
246707,160368,160368.0,160368.0,1.399697e+18,2022-08-04 15:51:36+00:00,1.555220e+18,en,6.0,1.0,2.0,1.0,unk,#TAIWAN #CHINA #PELOSI #XI ALL COMPANIES IN TA...,0,0,2,1,1,1
124005,124005,124005.0,124005.0,1.576602e+18,2022-11-21 20:15:27+00:00,1.594787e+18,en,3.0,0.0,0.0,0.0,unk,Dm me for my dick boys and girls #straight #di...,1,0,2,1,1,1

In [ ]:
samples_2022.to_csv('samples_2022.csv', index=False)
# np.savetxt(r'samples_2020.txt', samples_2020.tweet, fmt='%d')

## 2020

In [ ]:
path_2020 = '/content/drive/MyDrive/#CHINA HATE/2020/labelled/2020.csv'
path_2021 = '/content/drive/MyDrive/#CHINA HATE/2021/labelled/2021.csv'

In [ ]:
df_2020 = pd.read_csv(path_2020)

In [ ]:
len_df = len(df_2020)
COVID_HATE_BERT_PREDS_bin = []
hateXplain_PREDS_bin = []

for i in range(len_df):
  if df_2020['COVID_HATE_BERT_PREDS'][i] == 2:
    COVID_HATE_BERT_PREDS_bin.append(1)
  else:
    COVID_HATE_BERT_PREDS_bin.append(0)
  
  if df_2020['hateXplain_PREDS'][i] == 0:
    hateXplain_PREDS_bin.append(1)
  else:
    hateXplain_PREDS_bin.append(0)

df_2020['COVID_HATE_BERT_PREDS_bin'] = COVID_HATE_BERT_PREDS_bin
df_2020['hateXplain_PREDS_bin'] = hateXplain_PREDS_bin

In [ ]:
voting_2020 = []

for i in range(len_df):

  votes = []
  votes.append(df_2020['COVID_HATE_BERT_PREDS_bin'][i])
  votes.append(df_2020['CARDIFFNLP_ROBERTA_PREDS'][i])
  votes.append(df_2020['hateXplain_PREDS_bin'][i])

  voting_2020.append(max(set(votes), key = votes.count))

df_2020['voting_results'] = voting_2020
Counter(voting_2020)

Counter({0: 1233620, 1: 2715})

In [ ]:
df_2020_hate = df_2020.loc[df_2020['voting_results']==1]
df_2020_hate

,Unnamed: 0,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,COVID_HATE_BERT_PREDS,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,date,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
897,897,253410837,2020-12-31 13:46:18+00:00,1344641029677277189,en,0,0,0,0,Twitter for Android,#china I have something you dont have.....A Bl...,2,1,1,2020-12-31,1,0,1
1030,1030,88689155,2020-12-31 12:40:41+00:00,1344624515293220866,en,0,0,0,0,Twitter for iPhone,U.S. demands release of Uighur doctor while Ch...,2,0,0,2020-12-31,1,1,1
2383,2383,95617159,2020-12-31 01:52:46+00:00,1344461463461658625,en,0,0,0,0,Twitter for Android,no #VIRUS no #WEAPON will save #CHINA in 2021....,2,1,1,2020-12-31,1,0,1
2889,2889,612976069,2020-12-30 19:25:05+00:00,1344363898846257159,en,0,0,0,0,Twitter for iPhone,#China #ChinaVirus #ChinaJoeBiden I hate we c...,2,0,0,2020-12-30,1,1,1
4003,4003,21236953,2020-12-30 10:52:16+00:00,1344234843681525760,en,1,0,0,1,Twitter Web App,We buy stuff from #China &amp; #Japan but yet ...,2,0,0,2020-12-30,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229557,329557,791440926707253248,2020-01-04 15:16:28+00:00,1213479314118840328,en,6,0,3,10,Twitter Web App,StopSale of #Aldicarb #Twostep !Killed a pride...,2,1,1,2020-01-04,1,0,1
1230428,330428,1178402412228419584,2020-01-04 02:30:18+00:00,1213286501972398081,en,0,0,0,0,Twitter Web Client,#America has about 30-40% of its population ma...,2,1,0,2020-01-04,1,1,1
1232210,332210,1404971276,2020-01-03 06:38:32+00:00,1212986584326426626,en,1,0,1,0,Twitter for Android,#XiJinping is committing atrocious #GenocideOf...,2,1,0,2020-01-03,1,1,1
1233811,333811,1193876422105812993,2020-01-02 13:02:03+00:00,1212720710449270784,en,0,0,0,0,IFTTT,Porn malay free Meet and Fuck Magic Book 1 #gi...,2,0,0,2020-01-02,1,1,1
1234964,334964,1211421742796701696,2020-01-01 23:36:26+00:00,1212517971614146560,en,0,0,0,0,Twitter for Android,#China\n#China_is_terrorist\n\nWhy are Turks s...,2,1,2,2020-01-01,1,0,1

In [ ]:
# from random import sample
  
# tweets_2020 = list(df_2020_hate['tweet'])
# samples = sample(tweets_2020, 800)

In [ ]:
samples_2020 = df_2020_hate.sample(n=800)
samples_2020

,Unnamed: 0,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,COVID_HATE_BERT_PREDS,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,date,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
863649,263649,216712704,2020-04-09 18:49:10+00:00,1248322075489718272,en,0,0,0,0,Twitter for Android,So Sad ! China Evicts Africans from their Home...,0,1,0,2020-04-09,0,1,1
557069,257069,1145106102360649730,2020-06-20 00:20:50+00:00,1274135082710773761,en,4,0,1,2,Twitter for Android,This bullshit has gone on long enough ! \nThat...,2,1,2,2020-06-20,1,0,1
793568,193568,213827781,2020-04-20 21:24:18+00:00,1252347385331646464,en,1,0,0,0,Twitter for Android,Chinese should have invented a sexual intercou...,2,1,1,2020-04-20,1,0,1
335373,35373,1201595808564600834,2020-08-19 13:17:30+00:00,1296073809158701056,en,0,0,0,0,Twitter for Android,Stop torturing and killing and eating #dogs an...,2,0,0,2020-08-19,1,1,1
588309,288309,2225244115,2020-06-16 07:32:07+00:00,1272794066447523845,en,19,0,0,2,Twitter for Android,#China is showing too much aggression. In Galw...,2,1,0,2020-06-16,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586880,286880,1002450271769976833,2020-06-16 09:34:53+00:00,1272824963758620672,en,0,0,1,0,Twitter for Android,First corona(Chinese virus) now dispute in bor...,2,1,2,2020-06-16,1,0,1
945400,45400,1241035188521578496,2020-03-22 10:02:20+00:00,1241666514157277186,en,0,0,0,1,Twitter for Android,Does the hard competition between #America and...,2,0,0,2020-03-22,1,1,1
786509,186509,44683313,2020-04-22 14:39:34+00:00,1252970303220842496,en,0,0,0,0,Instagram,#China won't let Black Folks in there stores ....,2,1,1,2020-04-22,1,0,1
834989,234989,1009267974564282368,2020-04-13 02:08:23+00:00,1249519773970395137,en,3,0,1,0,Twitter Web App,Lol at stupid bots trying to make their countr...,2,1,1,2020-04-13,1,0,1
826171,226171,912084331,2020-04-14 08:19:54+00:00,1249975655476781056,en,0,0,0,0,Twitter for iPhone,The #NaziChineseGov is forccebly moving young ...,2,1,2,2020-04-14,1,0,1

In [ ]:
samples_2020.to_csv('samples_2020.csv', index=False)
# np.savetxt(r'samples_2020.txt', samples_2020.tweet, fmt='%d')

In [ ]:
# samples_2020['tweet'].to_csv('samples_2020.txt', sep=' ')

In [ ]:
with open('samples_2020.txt', 'w') as f:
    for tweet in samples_2020['tweet']:
        f.write(f"{tweet}\n")

In [ ]:
# ! cat samples_2020.txt

## 2021

In [ ]:
df_2021 = pd.read_csv(path_2021, lineterminator='\n')
df_2021

In [ ]:
len_df = len(df_2021)
COVID_HATE_BERT_PREDS_bin = []
hateXplain_PREDS_bin = []

for i in range(len_df):
  if df_2021['COVID_HATE_BERT_PREDS'][i] == 2:
    COVID_HATE_BERT_PREDS_bin.append(1)
  else:
    COVID_HATE_BERT_PREDS_bin.append(0)
  
  if df_2021['hateXplain_PREDS'][i] == 0:
    hateXplain_PREDS_bin.append(1)
  else:
    hateXplain_PREDS_bin.append(0)

df_2021['COVID_HATE_BERT_PREDS_bin'] = COVID_HATE_BERT_PREDS_bin
df_2021['hateXplain_PREDS_bin'] = hateXplain_PREDS_bin

In [ ]:
voting_2021 = []

for i in range(len_df):

  votes = []
  votes.append(df_2021['COVID_HATE_BERT_PREDS_bin'][i])
  votes.append(df_2021['CARDIFFNLP_ROBERTA_PREDS'][i])
  votes.append(df_2021['hateXplain_PREDS_bin'][i])

  voting_2021.append(max(set(votes), key = votes.count))

df_2021['voting_results'] = voting_2021
Counter(voting_2021)

Counter({0: 934924, 1: 1074})

In [ ]:
df_2021_hate = df_2021.loc[df_2021['voting_results']==1]
df_2021_hate

,Unnamed: 0,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,COVID_HATE_BERT_PREDS,date,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
957,957,1443969757162704898,2021-12-31 13:34:59+00:00,1476909754014474247,en,0,0,0,0,Twitter for iPhone,#Tigray forces are calling for a ceasefire. Th...,1,0,0,2021-12-31,0,1,1
2024,2024,1372788451502813185,2021-12-31 05:55:13+00:00,1476794050330177579,en,3,0,0,0,Twitter for Android,Haile Selassie: Starved and Bombed Tigray with...,0,0,2,2021-12-31,1,1,1
2360,2360,1005474816386785280,2021-12-31 02:38:29+00:00,1476744538857299975,en,0,0,0,0,Twitter Web App,"THE VACCINES DON'T, DON'T STOP THE SPREAD OF C...",1,1,2,2021-12-31,1,0,1
2515,2515,1336344727340388356,2021-12-31 01:01:17+00:00,1476720078829887488,en,0,0,0,0,Twitter for Android,THE #CONSERTIUMS OF ALL #REACTIONARIES ; the #...,1,0,0,2021-12-31,0,1,1
3216,3216,1423692128568320006,2021-12-30 17:16:00+00:00,1476602985828405281,en,16,0,0,2,Twitter for Android,"I'm living GuangZhou,come dm me\n#nsfw #cock #...",0,0,2,2021-12-30,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928909,210742,1315264604851908609,2021-01-04 20:10:44+00:00,1346187326062530563,en,1,0,0,0,Twitter for Android,Thanks #China sub human mongrels..,0,0,2,2021-01-04,1,1,1
932129,213962,1339817980482310144,2021-01-03 11:14:28+00:00,1345689982543962113,en,1,2,0,0,Twitter for Android,"Dear #China, keep your #Covid #ChinaVirus\nKee...",1,1,2,2021-01-03,1,0,1
932597,214430,1233833252777070593,2021-01-03 04:23:39+00:00,1345586598897967104,en,0,0,0,0,Twitter for Android,#Chinese are #terrorist #evilcriminals from h...,1,2,2,2021-01-03,1,0,1
932623,214456,1233833252777070593,2021-01-03 03:55:05+00:00,1345579408606818304,en,0,0,0,0,Twitter for Android,Hell yeah never back down. #DamnChina. #China ...,1,2,2,2021-01-03,1,0,1
933003,214836,2255480352,2021-01-02 20:02:09+00:00,1345460390327701504,en,0,0,0,0,Twitter for iPad,#China #AnimalAbusers have cashed in on Denmar...,1,0,2,2021-01-02,1,1,1

In [ ]:
samples_2021 = df_2021_hate.sample(n=800)
samples_2021

,Unnamed: 0,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,COVID_HATE_BERT_PREDS,date,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
879604,161437,1046076663363031040,2021-01-25 06:37:25+00:00,1353592795626303489,en,2,0,0,1,Twitter for Android,#NationalVotersDay #SarkaruVaariPaata #coronav...,1,1,2,2021-01-25,1,0,1
906794,188627,1346705736215142404,2021-01-13 20:06:14+00:00,1349447686534021120,en,2,0,1,0,Twitter,daily reminder that #china is genociding #uigh...,0,0,2,2021-01-13,1,1,1
736384,18217,855963462,2021-03-25 01:54:36+00:00,1374902503884619781,en,0,0,0,0,Twitter Web App,#China THE WORLD NEEDS TO GET OFF CHEEP SHIT A...,1,1,2,2021-03-25,1,0,1
509389,24171,1566751266,2021-06-21 11:32:33+00:00,1406938084063780872,en,10,1,4,18,Twitter for iPhone,"THE HORROR IS BEGUN, TODAY IS THE https://t.co...",1,1,2,2021-06-21,1,0,1
129860,129860,1357117870480719873,2021-11-11 17:18:20+00:00,1458846566148546593,en,1,1,0,1,Twitter for iPhone,This is How #CHINA destroying our mother land....,1,1,2,2021-11-11,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575045,89827,1274855931411599368,2021-05-27 18:49:17+00:00,1397988293522903041,en,1,0,0,0,Twitter for iPhone,China is unwilling to cooperate because they h...,1,2,2,2021-05-27,1,0,1
928270,210103,1324775547893960705,2021-01-05 03:59:13+00:00,1346305224487677952,en,0,0,0,0,Twitter for Android,So tomorrow we will find out if the USA will b...,1,0,0,2021-01-05,0,1,1
177942,177942,1288963746908590080,2021-10-23 18:46:19+00:00,1451983339976601602,en,156,1,4,48,Twitter Web App,White Man's Cum inside my Asian ass\n\n#WMAF #...,1,1,2,2021-10-23,1,0,1
224207,224207,1380325765879762944,2021-10-07 08:49:06+00:00,1446034838453047303,en,0,0,0,0,Twitter for Android,Haha scum #china is weak and like a baby \n\n@...,0,0,2,2021-10-07,1,1,1
923495,205328,271806250,2021-01-06 16:51:12+00:00,1346861888483840000,en,0,0,0,0,Twitter Web App,#NWO;#ThePrince;#TheBattle;#TheBeast...4 #Russ...,1,2,2,2021-01-06,1,0,1

In [ ]:
samples_2021.to_csv('samples_2021.csv', index=False)
# np.savetxt(r'samples_2020.txt', samples_2020.tweet, fmt='%d')

In [ ]:
with open('samples_2021.txt', 'w') as f:
    for tweet in samples_2021['tweet']:
        f.write(f"{tweet}\n")

In [ ]:
samples_2020.drop(columns=samples_2020.columns[:1], axis=1, inplace=True)
samples_2020

,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,COVID_HATE_BERT_PREDS,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,date,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
863649,216712704,2020-04-09 18:49:10+00:00,1248322075489718272,en,0,0,0,0,Twitter for Android,So Sad ! China Evicts Africans from their Home...,0,1,0,2020-04-09,0,1,1
557069,1145106102360649730,2020-06-20 00:20:50+00:00,1274135082710773761,en,4,0,1,2,Twitter for Android,This bullshit has gone on long enough ! \nThat...,2,1,2,2020-06-20,1,0,1
793568,213827781,2020-04-20 21:24:18+00:00,1252347385331646464,en,1,0,0,0,Twitter for Android,Chinese should have invented a sexual intercou...,2,1,1,2020-04-20,1,0,1
335373,1201595808564600834,2020-08-19 13:17:30+00:00,1296073809158701056,en,0,0,0,0,Twitter for Android,Stop torturing and killing and eating #dogs an...,2,0,0,2020-08-19,1,1,1
588309,2225244115,2020-06-16 07:32:07+00:00,1272794066447523845,en,19,0,0,2,Twitter for Android,#China is showing too much aggression. In Galw...,2,1,0,2020-06-16,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586880,1002450271769976833,2020-06-16 09:34:53+00:00,1272824963758620672,en,0,0,1,0,Twitter for Android,First corona(Chinese virus) now dispute in bor...,2,1,2,2020-06-16,1,0,1
945400,1241035188521578496,2020-03-22 10:02:20+00:00,1241666514157277186,en,0,0,0,1,Twitter for Android,Does the hard competition between #America and...,2,0,0,2020-03-22,1,1,1
786509,44683313,2020-04-22 14:39:34+00:00,1252970303220842496,en,0,0,0,0,Instagram,#China won't let Black Folks in there stores ....,2,1,1,2020-04-22,1,0,1
834989,1009267974564282368,2020-04-13 02:08:23+00:00,1249519773970395137,en,3,0,1,0,Twitter Web App,Lol at stupid bots trying to make their countr...,2,1,1,2020-04-13,1,0,1
826171,912084331,2020-04-14 08:19:54+00:00,1249975655476781056,en,0,0,0,0,Twitter for iPhone,The #NaziChineseGov is forccebly moving young ...,2,1,2,2020-04-14,1,0,1

In [ ]:
samples_2021.drop(columns=samples_2021.columns[:1], axis=1, inplace=True)
samples_2021

,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,COVID_HATE_BERT_PREDS,date,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
879604,1046076663363031040,2021-01-25 06:37:25+00:00,1353592795626303489,en,2,0,0,1,Twitter for Android,#NationalVotersDay #SarkaruVaariPaata #coronav...,1,1,2,2021-01-25,1,0,1
906794,1346705736215142404,2021-01-13 20:06:14+00:00,1349447686534021120,en,2,0,1,0,Twitter,daily reminder that #china is genociding #uigh...,0,0,2,2021-01-13,1,1,1
736384,855963462,2021-03-25 01:54:36+00:00,1374902503884619781,en,0,0,0,0,Twitter Web App,#China THE WORLD NEEDS TO GET OFF CHEEP SHIT A...,1,1,2,2021-03-25,1,0,1
509389,1566751266,2021-06-21 11:32:33+00:00,1406938084063780872,en,10,1,4,18,Twitter for iPhone,"THE HORROR IS BEGUN, TODAY IS THE https://t.co...",1,1,2,2021-06-21,1,0,1
129860,1357117870480719873,2021-11-11 17:18:20+00:00,1458846566148546593,en,1,1,0,1,Twitter for iPhone,This is How #CHINA destroying our mother land....,1,1,2,2021-11-11,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575045,1274855931411599368,2021-05-27 18:49:17+00:00,1397988293522903041,en,1,0,0,0,Twitter for iPhone,China is unwilling to cooperate because they h...,1,2,2,2021-05-27,1,0,1
928270,1324775547893960705,2021-01-05 03:59:13+00:00,1346305224487677952,en,0,0,0,0,Twitter for Android,So tomorrow we will find out if the USA will b...,1,0,0,2021-01-05,0,1,1
177942,1288963746908590080,2021-10-23 18:46:19+00:00,1451983339976601602,en,156,1,4,48,Twitter Web App,White Man's Cum inside my Asian ass\n\n#WMAF #...,1,1,2,2021-10-23,1,0,1
224207,1380325765879762944,2021-10-07 08:49:06+00:00,1446034838453047303,en,0,0,0,0,Twitter for Android,Haha scum #china is weak and like a baby \n\n@...,0,0,2,2021-10-07,1,1,1
923495,271806250,2021-01-06 16:51:12+00:00,1346861888483840000,en,0,0,0,0,Twitter Web App,#NWO;#ThePrince;#TheBattle;#TheBeast...4 #Russ...,1,2,2,2021-01-06,1,0,1

In [ ]:
data = pd.read_csv('/content/samples_2020.csv')
data

,author id,created_at,id,lang,like_count,quote_count,reply_count,retweet_count,source,tweet,COVID_HATE_BERT_PREDS,CARDIFFNLP_ROBERTA_PREDS,hateXplain_PREDS,date,COVID_HATE_BERT_PREDS_bin,hateXplain_PREDS_bin,voting_results
0,216712704,2020-04-09 18:49:10+00:00,1248322075489718272,en,0,0,0,0,Twitter for Android,So Sad ! China Evicts Africans from their Home...,0,1,0,2020-04-09,0,1,1
1,1145106102360649730,2020-06-20 00:20:50+00:00,1274135082710773761,en,4,0,1,2,Twitter for Android,This bullshit has gone on long enough ! \nThat...,2,1,2,2020-06-20,1,0,1
2,213827781,2020-04-20 21:24:18+00:00,1252347385331646464,en,1,0,0,0,Twitter for Android,Chinese should have invented a sexual intercou...,2,1,1,2020-04-20,1,0,1
3,1201595808564600834,2020-08-19 13:17:30+00:00,1296073809158701056,en,0,0,0,0,Twitter for Android,Stop torturing and killing and eating #dogs an...,2,0,0,2020-08-19,1,1,1
4,2225244115,2020-06-16 07:32:07+00:00,1272794066447523845,en,19,0,0,2,Twitter for Android,#China is showing too much aggression. In Galw...,2,1,0,2020-06-16,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,1002450271769976833,2020-06-16 09:34:53+00:00,1272824963758620672,en,0,0,1,0,Twitter for Android,First corona(Chinese virus) now dispute in bor...,2,1,2,2020-06-16,1,0,1
796,1241035188521578496,2020-03-22 10:02:20+00:00,1241666514157277186,en,0,0,0,1,Twitter for Android,Does the hard competition between #America and...,2,0,0,2020-03-22,1,1,1
797,44683313,2020-04-22 14:39:34+00:00,1252970303220842496,en,0,0,0,0,Instagram,#China won't let Black Folks in there stores ....,2,1,1,2020-04-22,1,0,1
798,1009267974564282368,2020-04-13 02:08:23+00:00,1249519773970395137,en,3,0,1,0,Twitter Web App,Lol at stupid bots trying to make their countr...,2,1,1,2020-04-13,1,0,1
799,912084331,2020-04-14 08:19:54+00:00,1249975655476781056,en,0,0,0,0,Twitter for iPhone,The #NaziChineseGov is forccebly moving young ...,2,1,2,2020-04-14,1,0,1